t=[10,20,30,20,40]
print("Tuple:",t)
print("First element:",t[0])
print("Last element:",t[-1])
print("Length:",len(t))
print("Count of 20:",t.count(20))
print("Index of 30:",t.index(30))
print("Maximum:",max(t))
print("Minimum:",min(t))
print("Sum:",sum(t))
print("Is 40 present?",40 in t)
l=list(t)
print("Tuple converted to list:",l)
t2=tuple(l)
print("List converted to tuple:",t2)
