marks=[90,80,70,100,50,30,20]
print("original list:",marks)
print("length of the list:",len(marks))
marks.append(85)
print("after append:",marks)
marks.insert(1,95)
print("marks after insertion:",marks)
marks.remove(20)
print("marks after removal:",marks)
x=marks.pop()
print("list after popping:",marks)
print("number of 100 in list:",marks.count(100))
print("print the index of 50:",marks.index(50))
marks.reverse()
print("after reverse:",marks)
new_list=marks.copy()
print("copied list:",new_list)
marks.extend([60,55])
print("marks after extention:",marks)
print("highest value:",max(marks))
print("lowest value:",min(marks))
print("sum of all values:",sum(marks))
new_list.clear()
print("list after clear:",new_list)

